// ✅ 实际使用到的图标列表（请定期用脚本提取维护）
const usedIcons = [
  // mdi
  'mdi:help-circle',
  'mdi:translate',
  'mdi:wallet',
  'mdi:remote-desktop',
  'mdi:devices',
  'mdi:cog',
  'mdi:circle-slice-8',
  'mdi:alert-circle-outline',
  'mdi:eye',
  'mdi:eye-off',
  'mdi:content-copy',
  'mdi:cart-outline',
  'mdi:arrow-left',
  'mdi:lock',
  'mdi:qqchat',
  'mdi:youtube',
  'mdi:telegram',
  'mdi:discord',
  'mdi:twitter',
  'mdi:theme-light-dark',
  'mdi:mouse-off',
  'mdi:gamepad-variant',
  'mdi:information-outline',
  'mdi:arrow-right',
  'mdi:cart',

  // logos
  'logos:apple',
  'logos:ubuntu',
  'logos:debian',
  'logos:fedora',
  'logos:redhat',
  'logos:centos-icon',
  'logos:archlinux',
  'logos:opensuse',
  'logos:manjaro',
  'logos:linux-mint',
  'logos:oracle',
  'logos:raspberry-pi',
  'logos:solarwinds',
  'logos:freebsd',
  'logos:android-icon',
]
